server:
  port: 9090
  address: localhost
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/security-study?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jackson:
    date-format: yyyy-mm-dd
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 10MB
  mail:
    host: smtp.163.com
    username: javastudy111@163.com
    password: ADNMGCTHSQGDJLUE
    port: 465
    properties:
      from: javastudy111@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
mybatis-plus:
  mapper-locations: classpath:mapping/*